version: '3'
services:
  app:
    container_name: node-app
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./archive:/app/archive
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod